# Generated by Django 5.0.6 on 2024-06-29 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField(default=None)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default=None, max_length=255)),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None)),
                ('players', models.TextField(default=None)),
                ('satisfaction', models.IntegerField(default=None)),
                ('video', models.FileField(default=None, upload_to='videos')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='MyApp.child')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tag', models.IntegerField(choices=[(0, 'From Parent'), (1, 'From Child')], default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='MyApp.child')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Bullying victim'), (2, 'Bully')], default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MyApp.child')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_playtime', models.DurationField(blank=True, null=True)),
                ('break_time', models.DurationField(blank=True, null=True)),
                ('break_duration_time', models.DurationField(blank=True, null=True)),
                ('bad_words', models.TextField(blank=True, null=True)),
                ('presence_of_ai', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='MyApp.child')),
            ],
        ),
    ]
