# Generated by Django 5.0.6 on 2024-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(choices=[(0, 'under 12'), (1, '12-16'), (2, '16+')], default=0),
        ),
    ]
