# Generated by Django 5.0.6 on 2024-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
