# Generated by Django 5.0.6 on 2024-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_notification_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='break_duration_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='break_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='daily_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
