# Generated by Django 5.0.6 on 2024-06-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_setting_break_duration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bully_action',
            field=models.CharField(choices=[('exit', 'Exit from current game'), ('notice', 'Notice the behavior'), ('ignore', 'Ignore')], default='exit', max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='victim_action',
            field=models.CharField(choices=[('exit', 'Exit from current game'), ('comfort', 'Comforting Child'), ('ignore', 'Ignore')], default='exit', max_length=50),
        ),
    ]
