# Generated by Django 5.0.6 on 2024-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_setting_bully_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='video_url',
            field=models.URLField(default='https://youtu.be/YJDaypZl6Jk', null=True),
        ),
    ]
