# Generated by Django 5.0.6 on 2024-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_gamesession_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='urgent_notification',
            field=models.BooleanField(default=False),
        ),
    ]
