# Generated by Django 5.0.6 on 2024-07-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_setting_urgent_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextfileURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('textfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='MyApp.textfile')),
            ],
        ),
    ]
