# Generated by Django 5.0.6 on 2024-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_notification_game_url_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='break_duration_time',
            new_name='chat_break_duration_time',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='break_time',
            new_name='chat_break_time',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='bully_action',
            new_name='chat_bully_action',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='daily_playtime',
            new_name='chat_daily_playtime',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='presence_of_ai',
            new_name='chat_presence_of_ai',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='victim_action',
            new_name='chat_victim_action',
        ),
        migrations.AddField(
            model_name='setting',
            name='ed_break_duration_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ed_break_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ed_bully_action',
            field=models.CharField(choices=[('exit', 'BigBuddy verbal reminders for bad behavior AND exclude from the game'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit', max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='ed_daily_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ed_presence_of_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='ed_victim_action',
            field=models.CharField(choices=[('exit', 'BigBuddy verbal notice about bad behavior AND comfort child'), ('comfort', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='exit', max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='game_break_duration_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='game_break_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='game_bully_action',
            field=models.CharField(choices=[('exit', 'BigBuddy verbal reminders for bad behavior AND exclude from the game'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit', max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='game_daily_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='game_presence_of_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='game_victim_action',
            field=models.CharField(choices=[('exit', 'BigBuddy verbal notice about bad behavior AND comfort child'), ('comfort', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='exit', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'Enter game'), (3, 'Exit game'), (1, 'Victim'), (2, 'Bully')], default=0),
        ),
    ]
