# Generated by Django 5.0.6 on 2024-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_rename_break_duration_time_setting_chat_break_duration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='chat_bully_action',
            field=models.TextField(choices=[('exit', 'BigBuddy verbal reminders AND stop current chat'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='chat_victim_action',
            field=models.TextField(choices=[('exit', 'BigBuddy verbal notice, comfort your child AND stop current chat'), ('comfort', 'BigBuddy verbal notice AND comfort your child'), ('notice', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='comfort'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ed_bully_action',
            field=models.TextField(choices=[('exit', 'BigBuddy verbal reminders AND exclude from current session'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ed_victim_action',
            field=models.TextField(choices=[('exit', 'BigBuddy verbal reminders, comfort child AND exclude bully from current session'), ('comfort', 'BigBuddy verbal notice AND comfort your child'), ('notice', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='comfort'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='game_bully_action',
            field=models.TextField(choices=[('exit', 'BigBuddy verbal reminders, set points to 0 AND exclude from the game'), ('point', 'BigBuddy verbal reminders AND set points to 0'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='game_victim_action',
            field=models.TextField(choices=[('comfort', 'BigBuddy verbal notice, set points to 0 AND comfort child'), ('point', 'BigBuddy verbal reminders AND set bully points to 0'), ('notice', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='comfort'),
        ),
    ]
