# Generated by Django 5.0.6 on 2024-07-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_setting_chat_bully_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_playtime', models.IntegerField(blank=True, null=True)),
                ('break_time', models.IntegerField(blank=True, null=True)),
                ('break_duration_time', models.IntegerField(blank=True, null=True)),
                ('presence_of_ai', models.BooleanField(default=False)),
                ('bully_action', models.TextField(choices=[('exit', 'BigBuddy verbal reminders AND stop current chat'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit')),
                ('victim_action', models.TextField(choices=[('exit', 'BigBuddy verbal notice, comfort your child AND stop current chat'), ('comfort', 'BigBuddy verbal notice AND comfort your child'), ('notice', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='comfort')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_setting', to='MyApp.child')),
            ],
        ),
        migrations.CreateModel(
            name='EducationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_playtime', models.IntegerField(blank=True, null=True)),
                ('break_time', models.IntegerField(blank=True, null=True)),
                ('break_duration_time', models.IntegerField(blank=True, null=True)),
                ('presence_of_ai', models.BooleanField(default=False)),
                ('bully_action', models.TextField(choices=[('exit', 'BigBuddy verbal reminders AND exclude from current session'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit')),
                ('victim_action', models.TextField(choices=[('exit', 'BigBuddy verbal reminders, comfort child AND exclude bully from current session'), ('comfort', 'BigBuddy verbal notice AND comfort your child'), ('notice', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='comfort')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_setting', to='MyApp.child')),
            ],
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_playtime', models.IntegerField(blank=True, null=True)),
                ('break_time', models.IntegerField(blank=True, null=True)),
                ('break_duration_time', models.IntegerField(blank=True, null=True)),
                ('presence_of_ai', models.BooleanField(default=False)),
                ('bully_action', models.TextField(choices=[('exit', 'BigBuddy verbal reminders, set points to 0 AND exclude from the game'), ('point', 'BigBuddy verbal reminders AND set points to 0'), ('notice', 'BigBuddy verbal reminders for bad behavior'), ('ignore', 'No intervention')], default='exit')),
                ('victim_action', models.TextField(choices=[('comfort', 'BigBuddy verbal notice, set points to 0 AND comfort child'), ('point', 'BigBuddy verbal reminders AND set bully points to 0'), ('notice', 'BigBuddy verbal notice about bad behavior'), ('ignore', 'No intervention')], default='comfort')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_setting', to='MyApp.child')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_words', models.TextField(blank=True, null=True)),
                ('urgent_notification', models.CharField(choices=[('app', 'Just notice on APP'), ('bully', 'Notify me when child is bullying'), ('victim', 'Notify me when child is bullying victim')], default='app', max_length=50)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_setting', to='MyApp.child')),
            ],
        ),
    ]
