# Generated by Django 5.0.6 on 2024-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_chatsetting_educationsetting_gamesetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetting',
            name='presence_of_ai',
            field=models.CharField(choices=[('Always', 'Always'), ('bully', 'Only Appear when child is bullying'), ('victim', 'Only Appear when when child is bullying victim')], default='Always', max_length=50),
        ),
    ]
