# Generated by Django 5.0.6 on 2024-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_gamesetting_presence_of_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='presence_of_ai',
            field=models.CharField(choices=[('Always', 'Always'), ('bully', 'Only Appear when child is bullying'), ('victim', 'Only Appear when when child is bullying victim')], default='Always', max_length=50),
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='presence_of_ai',
            field=models.CharField(choices=[('Always', 'Always'), ('bully', 'Only Appear when child is bullying'), ('victim', 'Only Appear when when child is bullying victim')], default='Always', max_length=50),
        ),
    ]
