# Generated by Django 5.0.6 on 2024-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_alter_chatsetting_presence_of_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsetting',
            name='presence_of_ai',
            field=models.CharField(choices=[('Always', 'Always'), ('bully', 'Only Appear when child is bullying'), ('victim', 'Only Appear when child is bullying victim'), ('urgent', 'Only Appear when bully OR victim situations')], default='Always', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='presence_of_ai',
            field=models.CharField(choices=[('Always', 'Always'), ('bully', 'Only Appear when child is bullying'), ('victim', 'Only Appear when child is bullying victim'), ('urgent', 'Only Appear when bully OR victim situations')], default='Always', max_length=50),
        ),
    ]
