# Generated by Django 5.0.6 on 2024-07-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_alter_educationsetting_presence_of_ai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsetting',
            old_name='break_duration_time',
            new_name='chat_break_duration_time',
        ),
        migrations.RenameField(
            model_name='chatsetting',
            old_name='break_time',
            new_name='chat_break_time',
        ),
        migrations.RenameField(
            model_name='chatsetting',
            old_name='bully_action',
            new_name='chat_bully_action',
        ),
        migrations.RenameField(
            model_name='chatsetting',
            old_name='daily_playtime',
            new_name='chat_daily_playtime',
        ),
        migrations.RenameField(
            model_name='chatsetting',
            old_name='presence_of_ai',
            new_name='chat_presence_of_ai',
        ),
        migrations.RenameField(
            model_name='chatsetting',
            old_name='victim_action',
            new_name='chat_victim_action',
        ),
        migrations.RenameField(
            model_name='educationsetting',
            old_name='break_duration_time',
            new_name='edu_break_duration_time',
        ),
        migrations.RenameField(
            model_name='educationsetting',
            old_name='break_time',
            new_name='edu_break_time',
        ),
        migrations.RenameField(
            model_name='educationsetting',
            old_name='bully_action',
            new_name='edu_bully_action',
        ),
        migrations.RenameField(
            model_name='educationsetting',
            old_name='daily_playtime',
            new_name='edu_daily_playtime',
        ),
        migrations.RenameField(
            model_name='educationsetting',
            old_name='presence_of_ai',
            new_name='edu_presence_of_ai',
        ),
        migrations.RenameField(
            model_name='educationsetting',
            old_name='victim_action',
            new_name='edu_victim_action',
        ),
        migrations.RenameField(
            model_name='gamesetting',
            old_name='break_duration_time',
            new_name='game_break_duration_time',
        ),
        migrations.RenameField(
            model_name='gamesetting',
            old_name='break_time',
            new_name='game_break_time',
        ),
        migrations.RenameField(
            model_name='gamesetting',
            old_name='bully_action',
            new_name='game_bully_action',
        ),
        migrations.RenameField(
            model_name='gamesetting',
            old_name='daily_playtime',
            new_name='game_daily_playtime',
        ),
        migrations.RenameField(
            model_name='gamesetting',
            old_name='presence_of_ai',
            new_name='game_presence_of_ai',
        ),
        migrations.RenameField(
            model_name='gamesetting',
            old_name='victim_action',
            new_name='game_victim_action',
        ),
    ]
