# Generated by Django 5.0.6 on 2024-07-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_generalsetting_daily_playtime_artsetting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnesssetting',
            old_name='fit_break_duration_time',
            new_name='fitness_break_duration_time',
        ),
        migrations.RenameField(
            model_name='fitnesssetting',
            old_name='fit_break_time',
            new_name='fitness_break_time',
        ),
        migrations.RenameField(
            model_name='fitnesssetting',
            old_name='fit_daily_playtime',
            new_name='fitness_daily_playtime',
        ),
        migrations.RenameField(
            model_name='fitnesssetting',
            old_name='fit_presence_of_ai',
            new_name='fitness_presence_of_ai',
        ),
    ]
