# Generated by Django 5.0.6 on 2024-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_rename_fit_break_duration_time_fitnesssetting_fitness_break_duration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='processed_measures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
