# Generated by Django 5.0.6 on 2024-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_notification_processed_measures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='daily_playtime',
            field=models.IntegerField(default=240),
        ),
    ]
