# Generated by Django 5.0.6 on 2024-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0025_alter_generalsetting_daily_playtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsetting',
            name='art_daily_playtime',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='chat_daily_playtime',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='edu_daily_playtime',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='fitnesssetting',
            name='fitness_daily_playtime',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='game_daily_playtime',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='singlegamesetting',
            name='sgame_daily_playtime',
            field=models.IntegerField(default=240),
        ),
    ]
