# Generated by Django 5.0.6 on 2024-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_alter_artsetting_art_daily_playtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsetting',
            name='art_break_duration_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='chat_break_duration_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='edu_break_duration_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='fitnesssetting',
            name='fitness_break_duration_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='game_break_duration_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='singlegamesetting',
            name='sgame_break_duration_time',
            field=models.IntegerField(default=30),
        ),
    ]
