# Generated by Django 5.0.6 on 2024-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_alter_artsetting_art_break_duration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='bully_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='bully_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='victim_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='victim_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
