# Generated by Django 5.0.6 on 2024-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_gamesession_bully_info_gamesession_bully_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.IntegerField(choices=[(1, 'Multi-Player Game'), (2, 'One-Player Game'), (3, 'Education VR'), (4, 'Chat Platforms'), (5, 'Creative Development VR'), (6, 'Fitness VR')]),
        ),
    ]
